nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0

        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: Token

        security:
            - BearerAuth: []

    areas:
        path_patterns:
            - ^/api(?!/doc$)

    models:
        names:
            MeteorologyStationListItem:
                alias: MeteorologyStationListItem
                type: App\Dto\Api\MeteorologyStationListItem
            MeteorologyStationDetail:
                alias: MeteorologyStationDetail
                type: App\Dto\Api\MeteorologyStationDetail
