security:
    providers:
        dummy_provider:
            memory: null

    firewalls:
        api_docs:
            pattern: ^/api/(doc|doc\.json)$
            security: false

        api:
            pattern: ^/api/
            stateless: true
            custom_authenticator: App\Security\ApiKeyAuthenticator
            provider: dummy_provider

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc\.json$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: ROLE_API }
